### ISSUE TITLE
Clarify the need for Spring WebFlux

### ISSUE THREAD

**Issue by snicoll** [rabbitmq/hop#122]
I am a bit confused why this project relies on Spring and, in particular, Spring WebFlux. This doesn't sound right for something that can be used as a client to rabbit.

Due to the current dependency structure, simply adding this jar will signal to [Spring Boot that it has to start a web server](https://github.com/spring-projects/spring-boot/issues/12853). One might argue that the sole presence of `spring-webflux` is too weak but that ship has sailed unfortunately. 

What is the rationale for using Spring WebFlux?

**Comment by bclozel** [comment]
I agree with @snicoll here - `WebClient` is not designed to be distributed as an independent HTTP client library, but rather a piece of the WebFlux ecosystem. In comparison, the [cf-java-client](https://github.com/cloudfoundry/cf-java-client) has chosen to directly use `reactor-netty` just for that.

**Comment by michaelklishin** [comment]
So what are you saying, that we should not use `WebClient`? The rationale seems to be a poor design decision on the Spring Boot side. What should we use instead if we don't want to reinvent an asynchronous HTTP client?

**Comment by bclozel** [comment]
Using or not `WebClient` is your choice ultimately - we're joint pointing to the fact that Spring Framework bundled `WebClient` and the web framework in `spring-webflux` because `WebClient` is not meant to be used independently as a client library.

Spring Boot is adapting to that and auto-configures things given the presence of `spring-webflux`. The fact that hop depends on a web framework is the problem here.

In my previous comment, I mentioned [cf-java-client](https://github.com/cloudfoundry/cf-java-client), which is using `reactor-netty` directly. cf-java-client is basically doing exactly that, so not only you don't need to reinvent a client (`reactor-netty` provides one, this is the one being used by `WebClient` under the covers) but also cf-java-client should do have the kind of implementation that you'd have to write anyway. If anything, this would make this library lighter and less prone to dependency conflicts.

**Comment by garyrussell** [comment]
I had a discussion about this with @artembilan the other day (I can't find the dialog), but we concluded that we should probably make the `http-client` dep `optional` since using the management template is rather a corner case and users will have to opt-in. `spring-rabbit` currently doesn't use the webflux part (but we might consider adding it).

Unless, boot can exclude the transitive dep (since it won't - currently - affect `spring-rabbit`).

**Comment by acogoluegnes** [comment]
@garyrussell Thanks for the clarification. Any idea when you'll use the reactive client (so we can start the refactoring to Reactor Netty)?

**Comment by garyrussell** [comment]
@acogoluegnes We haven't decided yet (discussion here https://github.com/spring-projects/spring-amqp/issues/736 - which is what I couldn't find earlier).

It will likely be in our 2.1 release (later in the summer).

**Comment by bclozel** [comment]
@acogoluegnes I agree we should add something in the documentation and make that more clear.
It's perfectly fine to only use `WebClient` in a Spring application that's not a web app, but I think it should not be consumed by libraries that don't want to have a full web framework on their classpath.

**Comment by acogoluegnes** [comment]
OK, I suggest the following steps:
 * HOP 2.1: implement new reactive client based on Reactive Netty, deprecate `ReactiveClient` (Spring WebFlux-based), make Spring WebFlux dependency optional. Spring AMQP 2.1 could use this version.
 * HOP 3.0: remove `ReactiveClient`.

WDYT @michaelklishin @garyrussell?

**Comment by michaelklishin** [comment]
We are a tiny team and it's very unfortunate that we have to throw away the existing client and redo all that work. @acogoluegnes that schedule SGTM.

**Comment by rstoyanchev** [comment]
I would rather say the expectation is that where `RestTemplate` and `WebClient` are used, Spring Framework dependencies (spring-core, spring-context, spring-web) are already on the classpath. Or otherwise you don't mind having those dependencies.

If HOP is currently using the `RestTemplate`, then the decision to use the `WebClient` seems perfectly reasonable to me. The `WebClient` does provide a higher level API, a set of codecs, and pluggable support for HTTP clients ([Jetty](https://jira.spring.io/browse/SPR-15092), and [JDK HttpClient](https://jira.spring.io/browse/SPR-16469) in the works).

From the comments under https://github.com/spring-projects/spring-boot/issues/12853 I see that there is a way to indicate a non-web environment. Forgive me if this is a naive question but I'm wondering if there is room for improvement in how a decision is made whether to start a WebFlux server or not? Is there some way to know if spring-boot-starter-webflux is declared or not?

**Comment by acogoluegnes** [comment]
Thanks @rstoyanchev for clarification.

@bclozel We may keep the `WebClient` implementation and make the dependencies optional (#124). Users will just have to add the appropriate dependencies depending on the client they pick. We still plan to implement a client based on Reactor Netty though, it shouldn't be too much work.

**Comment by acogoluegnes** [comment]
@michaelklishin I agree, maintaining 3 clients is a substantive effort. My concern now is to provide an appropriate solution to people using HOP in a Spring WebFlux server application, e.g. to share resources between different `WebClient` instances. If we can easily do that with Reactor Netty `HttpClient`, I don't mind getting rid of HOP `WebClient` implementation. WDYT @rstoyanchev?

**Comment by michaelklishin** [comment]
@bclozel do you have a Spring doc link where it "acknowledges in its documentation that WebClient is not meant to be distributed as an independent HTTP client library"? From where I sit WebFlux is promoted heavily as a new Spring ecosystem feature. That's why we have adopted it.

**Comment by michaelklishin** [comment]
@acogoluegnes unfortunately we are in a "damned if we do [integrate with WebFlux], damned if we don't" kind of situation here. This library was first and foremost developed as a standalone one, not a Spring project dependency. It should therefore be as minimalistic as possible. All the nice integration bells and whistles should either be on the Spring side or maintained as separate optional projects.

Hop was never meant to be a multi-month active development effort for our team. One way to meet that goal is to make it as small as possible and let other projects provide various integration bits.
