### ISSUE TITLE
RabbitMq 3.7

### ISSUE THREAD

**Issue by SirWayne** [rabbitmq/hop#127]
Supports the client Rabbit MQ version 3.7, because RabbitMQ 3.6 is end of life?
https://www.rabbitmq.com/news.html#2018-03-08T01:00:00+00:00

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by SirWayne** [comment]
Oh sorry a lot, next time i will ask athe the googel group :)
